### ISSUE TITLE
Executable getting flagged on Virus Total

### ISSUE THREAD

**Issue by basavyr** [Axorax/keylock#2]
The executable `keylock.exe` is flagged as insecure if one scans it with Virus Total. Results can be seen [here](https://www.virustotal.com/gui/file/8858a0d6fced5f45c971b21be89489e0a361ed2e94a32450e4f32b062bf58c24).

Hash: `8858a0d6fced5f45c971b21be89489e0a361ed2e94a32450e4f32b062bf58c24`
![image](https://github.com/user-attachments/assets/075c3bff-f855-4d1a-bff2-4190b7a8e6de)

**Comment by Axorax** [comment]
Not sure on why that is. I have had similar issues happen when I used Tauri to build another project called livewinsize.

It's definitely a false positive. You can test the executable if you want to.

**Comment by basavyr** [comment]
Thanks for the feedback. My local security software did not flag anything. But I just thought it's worth giving an insight.
